### ISSUE TITLE
Tensorflow 2 version

### ISSUE THREAD

**Issue by deepgradient** [suinleelab/attributionpriors#1]
It's great work. Could you please add support for Tensorflow 2 since it's now available.

Moreover, Tensorflow 1 will be deprecated in future soon

**Comment by psturmfels** [comment]
Glad to hear you like the work! 

Apologies for taking so long to get to this issue. I had been meaning to update the code for TF 2/TF with eager execution for a while now, but hadn't gotten around to it until today. I've updated the repository with a new API for training TF 2-style models (tf.keras.layers API) with eager execution enabled.

Feel free to open another issue if the you find bugs with the new API, but for now, I'm closing this issue.

**Comment by deepgradient** [comment]
> Glad to hear you like the work!
> 
> Apologies for taking so long to get to this issue. I had been meaning to update the code for TF 2/TF with eager execution for a while now, but hadn't gotten around to it until today. I've updated the repository with a new API for training TF 2-style models (tf.keras.layers API) with eager execution enabled.
> 
> Feel free to open another issue if the you find bugs with the new API, but for now, I'm closing this issue.

Great work. Thanks for updating package so that it can support tensorflow 2.
