### ISSUE TITLE
Total derivative bug in integrated gradient implementation

### ISSUE THREAD

**Issue by Bonnevie** [suinleelab/attributionpriors#3]
First off, very interesting work on expected gradients and attribution priors.
was looking at using your integrated/expected gradient code, but think there is a bug. If you look at this part,

https://github.com/suinleelab/attributionpriors/blob/b66d65bf4c4783aabc49bdd1d2149da7a6fc8b6e/attributionpriors/eager_ops.py#L162-L181

note that the gradient is with respect to `current_input`, but that leads to an application of the chain rule since `current_input` appears in a nested expression. So you get the gradient of the model evaluated in the interpolated image *times* the derivative of the nested expression. Following the original paper and Proposition 1 there, you actually want the partial derivative of the model evaluated in the interpolated image times the `difference_from_reference`. So you are multiplying by one factor too many.

**Comment by psturmfels** [comment]
You are absolutely right - that is a bug! Good catch. Luckily, we've fixed this in our more recent repository which has slightly more up to date implementations of path explanations (https://github.com/suinleelab/path_explain/blob/master/path_explain/explainers/path_explainer_tf.py#L77).

As you said, there is an easy enough fix: simply move the computation of the interpolated input outside of the gradient tape, and then have the tape watch the interpolated input instead. I'll have to fix this when I get the chance.

**Comment by psturmfels** [comment]
This was fixed in https://github.com/suinleelab/attributionpriors/commit/2a68a33aac67f775c8bd4e19d93ae2b00f0a30b3
